# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b911cc4c5a62e8368512118a24b342b49fa48ecac5a3ab233c5d0a1ba0fa62ea994a8e5b863b69a301b7e8e7911a63c94cac6da46a6684de6e3d2d9ac473c8

test:
  secret_key_base: 0275562ce6132bbd816d8d8a42facd181cff7c5a6ea2a168e6897c8a89f3f5a8eeb1a9014fec4057ceb6723732d38e93a60e3c00d4032971c294168872ae0ff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
